
// TicketCommentResponse.java
package com.example.smartdeskbackend.dto.response.ticket;

import java.time.LocalDateTime;

public class TicketCommentResponse {

    private Long id;
    private String message;
    private Boolean isInternal;
    private Boolean isAutoGenerated;
    private String commentType;
    private Long authorId;
    private String authorName;
    private String authorRole;
    private LocalDateTime createdAt;

    // Constructors
    public TicketCommentResponse() {}

    // Getters and Setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getMessage() { return message; }
    public void setMessage(String message) { this.message = message; }

    public Boolean getIsInternal() { return isInternal; }
    public void setIsInternal(Boolean isInternal) { this.isInternal = isInternal; }

    public Boolean getIsAutoGenerated() { return isAutoGenerated; }
    public void setIsAutoGenerated(Boolean isAutoGenerated) { this.isAutoGenerated = isAutoGenerated; }

    public String getCommentType() { return commentType; }
    public void setCommentType(String commentType) { this.commentType = commentType; }

    public Long getAuthorId() { return authorId; }
    public void setAuthorId(Long authorId) { this.authorId = authorId; }

    public String getAuthorName() { return authorName; }
    public void setAuthorName(String authorName) { this.authorName = authorName; }

    public String getAuthorRole() { return authorRole; }
    public void setAuthorRole(String authorRole) { this.authorRole = authorRole; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
}